#!/usr/bin/env bash
set -euo pipefail

# Codex Builder - Execute implementation plans using Codex CLI

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"

# Default values
PLAN_FILE=""
OUTPUT_FILE=""
CWD=""
VERBOSE=false

# Usage message
usage() {
    cat <<'EOF'
Usage: execute-plan.sh <plan-file> [-o output.txt] [--cwd path] [--verbose]

Execute an implementation plan using Codex CLI for autonomous implementation.

Arguments:
  plan-file         Path to the plan markdown file (required)

Options:
  -o, --output      Output file for implementation report (default: /tmp/codex-build-report-YYYYMMDD-HHMMSS.txt)
  --cwd             Working directory for implementation (default: extracted from plan or current directory)
  --verbose         Show Codex's progress output
  -h, --help        Show this help message

Example:
  execute-plan.sh /tmp/auth-plan.md -o /tmp/auth-build.txt
  execute-plan.sh ~/.claude/plans/plan.md --verbose
EOF
}

# Generate timestamp for default output filename
timestamp() {
    date +"%Y%m%d-%H%M%S"
}

# Extract value from YAML frontmatter if present
extract_frontmatter() {
    local file="$1"
    local key="$2"

    # Read between --- markers and extract key (silently fail if no frontmatter)
    awk -v key="$key" '
        /^---$/ { if (in_fm) exit; in_fm=!in_fm; next }
        in_fm && $0 ~ "^" key ":" {
            sub("^" key ":[[:space:]]*", "");
            print;
            exit
        }
    ' "$file" 2>/dev/null || true
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        -o|--output)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        --cwd)
            CWD="$2"
            shift 2
            ;;
        --verbose)
            VERBOSE=true
            shift
            ;;
        -*)
            echo "Error: Unknown option: $1" >&2
            usage >&2
            exit 1
            ;;
        *)
            if [[ -z "$PLAN_FILE" ]]; then
                PLAN_FILE="$1"
            else
                echo "Error: Multiple plan files specified" >&2
                usage >&2
                exit 1
            fi
            shift
            ;;
    esac
done

# Check required argument
if [[ -z "$PLAN_FILE" ]]; then
    echo "Error: Plan file required" >&2
    usage >&2
    exit 1
fi

# Check plan file exists
if [[ ! -f "$PLAN_FILE" ]]; then
    echo "Error: Plan file not found: $PLAN_FILE" >&2
    exit 1
fi

# Set default output file if not specified
if [[ -z "$OUTPUT_FILE" ]]; then
    OUTPUT_FILE="/tmp/codex-build-report-$(timestamp).txt"
fi

# Extract CWD from plan frontmatter if not specified
if [[ -z "$CWD" ]]; then
    CWD=$(extract_frontmatter "$PLAN_FILE" "cwd")
    if [[ -z "$CWD" ]]; then
        CWD="$(pwd)"
    fi
fi

# Verify CWD exists
if [[ ! -d "$CWD" ]]; then
    echo "Error: Working directory not found: $CWD" >&2
    exit 1
fi

# Check if codex CLI is available
if ! command -v codex &> /dev/null; then
    echo "Error: 'codex' command not found. Please install Codex CLI first." >&2
    exit 1
fi

# Read plan content
PLAN_CONTENT="$(cat "$PLAN_FILE")"

# Create temporary file for instruction
INSTRUCTION_FILE="/tmp/codex-instruction-$(timestamp).txt"

cat > "$INSTRUCTION_FILE" <<'INSTRUCTION_EOF'
You are implementing a plan that was generated by Claude Code.

INSTRUCTION_EOF

echo "Plan file: $PLAN_FILE" >> "$INSTRUCTION_FILE"
echo "Working directory: $CWD" >> "$INSTRUCTION_FILE"
echo "" >> "$INSTRUCTION_FILE"
echo "Here is the complete plan:" >> "$INSTRUCTION_FILE"
echo "" >> "$INSTRUCTION_FILE"
cat "$PLAN_FILE" >> "$INSTRUCTION_FILE"
echo "" >> "$INSTRUCTION_FILE"

cat >> "$INSTRUCTION_FILE" <<'INSTRUCTION_EOF'

---

Your task:
1. Read and understand the complete implementation plan above
2. Execute ALL implementation steps in order
3. Create and modify files as specified in the plan
4. Follow the exact approach described in the plan
5. After completing each major step, note what was done

Important guidelines:
- Work in the specified working directory
- Follow the plan's implementation steps precisely
- If a step is unclear or blocked, document the issue and continue with other steps
- Create files with proper structure and imports
- Ensure code follows the patterns described in the plan
- Add appropriate error handling where specified
- Do not skip steps unless they are truly impossible

After completion, provide a summary:
- List all files created
- List all files modified
- Note any steps that could not be completed and why
- Suggest verification steps (tests to run, etc.)

Begin implementation now.
INSTRUCTION_EOF

# Show what we're about to do if verbose
if [[ "$VERBOSE" == true ]]; then
    echo "================================"
    echo "Codex Builder Execution"
    echo "================================"
    echo "Plan file: $PLAN_FILE"
    echo "Working directory: $CWD"
    echo "Output report: $OUTPUT_FILE"
    echo ""
    echo "Sending instruction to Codex..."
    echo ""
fi

# Execute Codex
EXECUTION_START=$(date +%s)

if [[ "$VERBOSE" == true ]]; then
    # Show output in real-time
    cd "$CWD"
    cat "$INSTRUCTION_FILE" | codex exec --full-auto 2>&1 | tee /tmp/codex-output-temp.txt
    CODEX_EXIT_CODE=${PIPESTATUS[1]}
    CODEX_OUTPUT=$(cat /tmp/codex-output-temp.txt)
    rm -f /tmp/codex-output-temp.txt
else
    # Suppress stderr
    cd "$CWD"
    CODEX_OUTPUT=$(cat "$INSTRUCTION_FILE" | codex exec --full-auto 2>&1)
    CODEX_EXIT_CODE=$?
fi

EXECUTION_END=$(date +%s)
EXECUTION_TIME=$((EXECUTION_END - EXECUTION_START))

# Clean up instruction file
rm -f "$INSTRUCTION_FILE"

# Check exit code
if [[ $CODEX_EXIT_CODE -ne 0 ]]; then
    echo "Error: codex exited with code $CODEX_EXIT_CODE" >&2
    if [[ "$VERBOSE" != true ]]; then
        echo "Run with --verbose to see error details" >&2
    fi

    cat > "$OUTPUT_FILE" <<REPORT_EOF
Codex Builder Implementation Report
====================================
Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
Plan file: $PLAN_FILE
Working directory: $CWD
Status: FAILED (exit code $CODEX_EXIT_CODE)

Error Output:
-------------
$CODEX_OUTPUT
REPORT_EOF

    echo "Error output saved to: $OUTPUT_FILE" >&2
    exit $CODEX_EXIT_CODE
fi

# Generate report
cat > "$OUTPUT_FILE" <<REPORT_EOF
Codex Builder Implementation Report
====================================
Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
Plan file: $PLAN_FILE
Working directory: $CWD
Execution time: ${EXECUTION_TIME}s

Implementation Output:
----------------------
$CODEX_OUTPUT

---
Status: COMPLETED
Execution time: ${EXECUTION_TIME} seconds

Next Steps:
-----------
1. Review the changes:
   cd $CWD
   git status
   git diff

2. Test the implementation:
   - Run relevant tests
   - Verify functionality
   - Check for errors

3. Commit if satisfied:
   git add -A
   git commit -m "Implement: [describe changes]"

4. Or rollback if needed:
   git checkout .
   git clean -fd
REPORT_EOF

# Show summary
if [[ "$VERBOSE" == true ]]; then
    echo ""
    echo "================================"
    echo "Execution Complete"
    echo "================================"
    echo "Time: ${EXECUTION_TIME}s"
    echo "Report saved to: $OUTPUT_FILE"
    echo ""
fi

# Output the file path (for script chaining)
echo "$OUTPUT_FILE"
